package de.kugi.dev.battleoftheuniverse.catalog;

import com.networknt.schema.Error;
import com.networknt.schema.Schema;
import com.networknt.schema.SchemaRegistry;
import com.networknt.schema.SpecificationVersion;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.Collections;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Owns the game-balance catalog (buildings, ships, technologies). Definitions are
 * seeded from {@code classpath:catalog/*.json} into a writable {@code ./config/catalog}
 * directory on first startup, validated against the schema generated by
 * {@link JsonSchemaService}, and kept in memory for fast lookup by every other module.
 */
@Service
@RequiredArgsConstructor
public class CatalogService {

    private final JsonSchemaService jsonSchemaService;
    private final JsonMapper jsonMapper = JsonMapper.builder().build();
    /** Configurable so tests can point it at a throwaway directory instead of the real, gitignored ./config/catalog a dev server also uses. */
    @Value("${game.catalog.dir:config/catalog}")
    private String catalogDirPath;
    private Path catalogDir;

    /**
     * Each map is replaced wholesale (never mutated in place) and published via a volatile
     * write, so a concurrent reader always sees either the old or the new catalog in full -
     * never a partially-cleared one mid-{@link #save}. A {@link LinkedHashMap} preserves JSON
     * declaration order for {@link #buildings()}/{@link #ships()}/etc, unlike the previous
     * {@code ConcurrentHashMap}, whose iteration order was incidental.
     */
    private volatile Map<CatalogType, JsonNode> rawData = Map.of();
    private volatile Map<String, BuildingDefinition> buildingsByKey = Map.of();
    private volatile Map<String, ShipDefinition> shipsByKey = Map.of();
    private volatile Map<String, TechnologyDefinition> technologiesByKey = Map.of();
    private volatile Map<String, DefenseDefinition> defensesByKey = Map.of();

    @PostConstruct
    void loadAll() {
        catalogDir = Path.of(catalogDirPath);
        for (CatalogType type : CatalogType.values()) {
            reload(type);
        }
    }

    public List<BuildingDefinition> buildings() {
        return List.copyOf(buildingsByKey.values());
    }

    public BuildingDefinition building(String key) {
        BuildingDefinition definition = buildingsByKey.get(key);
        if (definition == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unknown building: " + key);
        }
        return definition;
    }

    public List<ShipDefinition> ships() {
        return List.copyOf(shipsByKey.values());
    }

    public ShipDefinition ship(String key) {
        ShipDefinition definition = shipsByKey.get(key);
        if (definition == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unknown ship: " + key);
        }
        return definition;
    }

    public List<TechnologyDefinition> technologies() {
        return List.copyOf(technologiesByKey.values());
    }

    public TechnologyDefinition technology(String key) {
        TechnologyDefinition definition = technologiesByKey.get(key);
        if (definition == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unknown technology: " + key);
        }
        return definition;
    }

    public List<DefenseDefinition> defenses() {
        return List.copyOf(defensesByKey.values());
    }

    public DefenseDefinition defense(String key) {
        DefenseDefinition definition = defensesByKey.get(key);
        if (definition == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unknown defense: " + key);
        }
        return definition;
    }

    public ResourceCost costFor(BuildingDefinition definition, int targetLevel) {
        return definition.baseCost().scaled(Math.pow(definition.costGrowthFactor(), targetLevel - 1));
    }

    public Duration buildTimeFor(BuildingDefinition definition, int targetLevel) {
        return Duration.ofSeconds((long) definition.baseBuildTimeSeconds() * targetLevel);
    }

    public ResourceCost costFor(TechnologyDefinition definition, int targetLevel) {
        return definition.baseCost().scaled(Math.pow(definition.costGrowthFactor(), targetLevel - 1));
    }

    public Duration researchTimeFor(TechnologyDefinition definition, int targetLevel) {
        return Duration.ofSeconds((long) definition.baseResearchTimeSeconds() * targetLevel);
    }

    /**
     * Resource units produced per hour by a building at the given level. Every level - including
     * 0, before it's ever been upgraded - produces a base amount; each additional level adds
     * another full increment on top, rather than production only starting at level 1.
     */
    public double productionPerHour(BuildingDefinition definition, int level) {
        return definition.baseProductionPerLevel() * (level + 1);
    }

    public JsonNode schemaFor(CatalogType type) {
        return jsonSchemaService.schemaFor(type.catalogClass());
    }

    public JsonNode currentData(CatalogType type) {
        return rawData.get(type);
    }

    /**
     * Schema validation alone isn't enough to guarantee {@code newData} can actually become the
     * target record type (e.g. a schema-optional field can still be a required Java primitive) -
     * {@link #applyToMemory} is called *before* writing to disk specifically so a payload that
     * passes the schema but fails deserialization is rejected as a clean 400 instead of being
     * persisted to the live catalog file and only failing on the next server restart.
     */
    public synchronized void save(CatalogType type, JsonNode newData) {
        validate(type, newData);
        try {
            applyToMemory(type, newData);
        } catch (RuntimeException e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid catalog data for " + type + ": " + e.getMessage(), e);
        }
        try {
            Files.createDirectories(catalogDir);
            Files.writeString(catalogDir.resolve(type.fileName()), newData.toPrettyString());
        } catch (IOException e) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Could not persist catalog", e);
        }
    }

    private void reload(CatalogType type) {
        Path livePath = catalogDir.resolve(type.fileName());
        JsonNode data;
        try {
            if (Files.notExists(livePath)) {
                Files.createDirectories(catalogDir);
                try (InputStream seed = new ClassPathResource("catalog/" + type.fileName()).getInputStream()) {
                    Files.write(livePath, seed.readAllBytes());
                }
            }
            data = jsonMapper.readTree(livePath.toFile());
        } catch (IOException e) {
            throw new IllegalStateException("Could not load catalog " + type, e);
        }
        validate(type, data);
        try {
            applyToMemory(type, data);
        } catch (RuntimeException e) {
            // Unlike save()'s ResponseStatusException, a startup failure isn't a web request to
            // reject - it's a corrupt live file that needs fixing before the server can run at
            // all, so this keeps the original exception type and cause instead of flattening it
            // into an HTTP-shaped message string.
            throw new IllegalStateException("Could not load catalog " + type + " into memory at startup", e);
        }
    }

    /**
     * Deserializes into the target record type and swaps it into the in-memory maps. Throws
     * whatever {@link RuntimeException} deserialization/mapping produced - {@link #save} and
     * {@link #reload} each translate that into whatever's appropriate for their own caller.
     */
    private void applyToMemory(CatalogType type, JsonNode data) {
        switch (type) {
            case BUILDINGS -> {
                BuildingCatalog catalog = jsonMapper.treeToValue(data, BuildingCatalog.class);
                buildingsByKey = orderedByKey(catalog.buildings(), BuildingDefinition::key);
            }
            case SHIPS -> {
                ShipCatalog catalog = jsonMapper.treeToValue(data, ShipCatalog.class);
                shipsByKey = orderedByKey(catalog.ships(), ShipDefinition::key);
            }
            case TECHNOLOGIES -> {
                TechnologyCatalog catalog = jsonMapper.treeToValue(data, TechnologyCatalog.class);
                technologiesByKey = orderedByKey(catalog.technologies(), TechnologyDefinition::key);
            }
            case DEFENSES -> {
                DefenseCatalog catalog = jsonMapper.treeToValue(data, DefenseCatalog.class);
                defensesByKey = orderedByKey(catalog.defenses(), DefenseDefinition::key);
            }
        }
        Map<CatalogType, JsonNode> updatedRawData = new EnumMap<>(CatalogType.class);
        updatedRawData.putAll(rawData);
        updatedRawData.put(type, data);
        rawData = Collections.unmodifiableMap(updatedRawData);
    }

    /** Preserves declaration order from the source JSON, unlike a plain {@code Collectors.toMap}/{@code ConcurrentHashMap}. */
    private <T> Map<String, T> orderedByKey(List<T> values, Function<T, String> keyFn) {
        Map<String, T> ordered = new LinkedHashMap<>();
        for (T value : values) {
            ordered.put(keyFn.apply(value), value);
        }
        return Collections.unmodifiableMap(ordered);
    }

    private void validate(CatalogType type, JsonNode data) {
        Schema schema = SchemaRegistry.withDefaultDialect(SpecificationVersion.DRAFT_7)
                .getSchema(schemaFor(type));
        List<Error> errors = schema.validate(data);
        if (!errors.isEmpty()) {
            String message = errors.stream().map(Error::getMessage).collect(Collectors.joining("; "));
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid catalog data for " + type + ": " + message);
        }
    }
}
