package de.kugi.dev.battleoftheuniverse.catalog;

import com.networknt.schema.Error;
import com.networknt.schema.Schema;
import com.networknt.schema.SchemaRegistry;
import com.networknt.schema.SpecificationVersion;
import jakarta.annotation.PostConstruct;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

/**
 * Owns the game-balance catalog (buildings, ships, technologies). Definitions are
 * seeded from {@code classpath:catalog/*.json} into a writable {@code ./config/catalog}
 * directory on first startup, validated against the schema generated by
 * {@link JsonSchemaService}, and kept in memory for fast lookup by every other module.
 */
@Service
public class CatalogService {

    private final JsonSchemaService jsonSchemaService;
    private final JsonMapper jsonMapper = JsonMapper.builder().build();
    private final Path catalogDir = Path.of("config", "catalog");

    private final Map<CatalogType, JsonNode> rawData = new ConcurrentHashMap<>();
    private final Map<String, BuildingDefinition> buildingsByKey = new ConcurrentHashMap<>();
    private final Map<String, ShipDefinition> shipsByKey = new ConcurrentHashMap<>();
    private final Map<String, TechnologyDefinition> technologiesByKey = new ConcurrentHashMap<>();

    public CatalogService(JsonSchemaService jsonSchemaService) {
        this.jsonSchemaService = jsonSchemaService;
    }

    @PostConstruct
    void loadAll() {
        for (CatalogType type : CatalogType.values()) {
            reload(type);
        }
    }

    public List<BuildingDefinition> buildings() {
        return List.copyOf(buildingsByKey.values());
    }

    public BuildingDefinition building(String key) {
        BuildingDefinition definition = buildingsByKey.get(key);
        if (definition == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unknown building: " + key);
        }
        return definition;
    }

    public List<ShipDefinition> ships() {
        return List.copyOf(shipsByKey.values());
    }

    public ShipDefinition ship(String key) {
        ShipDefinition definition = shipsByKey.get(key);
        if (definition == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unknown ship: " + key);
        }
        return definition;
    }

    public List<TechnologyDefinition> technologies() {
        return List.copyOf(technologiesByKey.values());
    }

    public TechnologyDefinition technology(String key) {
        TechnologyDefinition definition = technologiesByKey.get(key);
        if (definition == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unknown technology: " + key);
        }
        return definition;
    }

    public ResourceCost costFor(BuildingDefinition definition, int targetLevel) {
        return definition.baseCost().scaled(Math.pow(definition.costGrowthFactor(), targetLevel - 1));
    }

    public Duration buildTimeFor(BuildingDefinition definition, int targetLevel) {
        return Duration.ofSeconds((long) definition.baseBuildTimeSeconds() * targetLevel);
    }

    public ResourceCost costFor(TechnologyDefinition definition, int targetLevel) {
        return definition.baseCost().scaled(Math.pow(definition.costGrowthFactor(), targetLevel - 1));
    }

    public Duration researchTimeFor(TechnologyDefinition definition, int targetLevel) {
        return Duration.ofSeconds((long) definition.baseResearchTimeSeconds() * targetLevel);
    }

    /** Resource units produced per hour by a building at the given level. */
    public double productionPerHour(BuildingDefinition definition, int level) {
        return definition.baseProductionPerLevel() * level;
    }

    public JsonNode schemaFor(CatalogType type) {
        return jsonSchemaService.schemaFor(type.catalogClass());
    }

    public JsonNode currentData(CatalogType type) {
        return rawData.get(type);
    }

    public synchronized void save(CatalogType type, JsonNode newData) {
        validate(type, newData);
        try {
            Files.createDirectories(catalogDir);
            Files.writeString(catalogDir.resolve(type.fileName()), newData.toPrettyString());
        } catch (IOException e) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Could not persist catalog", e);
        }
        reload(type);
    }

    private void reload(CatalogType type) {
        Path livePath = catalogDir.resolve(type.fileName());
        JsonNode data;
        try {
            if (Files.notExists(livePath)) {
                Files.createDirectories(catalogDir);
                try (InputStream seed = new ClassPathResource("catalog/" + type.fileName()).getInputStream()) {
                    Files.write(livePath, seed.readAllBytes());
                }
            }
            data = jsonMapper.readTree(livePath.toFile());
        } catch (IOException e) {
            throw new IllegalStateException("Could not load catalog " + type, e);
        }
        validate(type, data);
        rawData.put(type, data);

        switch (type) {
            case BUILDINGS -> {
                BuildingCatalog catalog = jsonMapper.treeToValue(data, BuildingCatalog.class);
                replaceAll(buildingsByKey, catalog.buildings(), BuildingDefinition::key);
            }
            case SHIPS -> {
                ShipCatalog catalog = jsonMapper.treeToValue(data, ShipCatalog.class);
                replaceAll(shipsByKey, catalog.ships(), ShipDefinition::key);
            }
            case TECHNOLOGIES -> {
                TechnologyCatalog catalog = jsonMapper.treeToValue(data, TechnologyCatalog.class);
                replaceAll(technologiesByKey, catalog.technologies(), TechnologyDefinition::key);
            }
        }
    }

    private <T> void replaceAll(Map<String, T> target, List<T> values, java.util.function.Function<T, String> keyFn) {
        target.clear();
        target.putAll(values.stream().collect(Collectors.toMap(keyFn, v -> v)));
    }

    private void validate(CatalogType type, JsonNode data) {
        Schema schema = SchemaRegistry.withDefaultDialect(SpecificationVersion.DRAFT_7)
                .getSchema(schemaFor(type));
        List<Error> errors = schema.validate(data);
        if (!errors.isEmpty()) {
            String message = errors.stream().map(Error::getMessage).collect(Collectors.joining("; "));
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid catalog data for " + type + ": " + message);
        }
    }
}
