spring:
  application:
    name: battleoftheuniverse
  profiles:
    default: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

game:
  cors:
    allowed-origins: http://localhost:4200
