spring:
  datasource:
    url: jdbc:h2:file:./data/battleoftheuniverse;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

game:
  dev:
    seed-accounts: true
    admin:
      username: admin
      email: admin@battleoftheuniverse.local
      password: admin123
    player:
      username: player
      email: player@battleoftheuniverse.local
      password: player123

logging:
  level:
    de.kugi.dev.battleoftheuniverse: DEBUG
